language: rust
script:
  - cd choose; cargo build --verbose; cargo test --verbose; cd ..
  - cd ddg; cargo build --verbose; cargo test --verbose; cd ..
  - cd keybase; cargo build --verbose; cargo test --verbose; cd ..
  - cd presence; cargo build --verbose; cargo test --verbose; cd ..
  - cd puppet; cargo build --verbose; cargo test --verbose; cd ..
  - cd sys; cargo build --verbose; cargo test --verbose; cd ..
  - cd tell; cargo build --verbose; cargo test --verbose; cd ..
  - cd users; cargo build --verbose; cargo test --verbose; cd ..
notifications:
  email:
    on_success: never
  irc:
    channels:
      - "irc.fyrechat.net#vana-commits"
    template:
      - "%{repository_slug}/%{branch} (%{commit} - %{author}): %{message}"
    skip_join: true
