language: rust
script:
  - for d in *; do if [ -d "$d" ]; then pushd "$d"; cargo build --verbose; cargo test --verbose; popd; fi done
notifications:
  email:
    on_success: never
  irc:
    channels:
      - "irc.fyrechat.net#vana-commits"
    template:
      - "%{repository_slug}/%{branch} (%{commit} - %{author}): %{message}"
    skip_join: true
