[package]

name = "libawebot"
version = "0.0.1"
authors = ["Aaron Weiss <aaronweiss74@gmail.com>"]

[lib]

name = "libawebot"
crate-type = ["dylib"]

[dependencies.irc]

git = "https://github.com/aaronweiss74/irc.git"
