[package]

name = "sys"
version = "0.0.1"
authors = ["Aaron Weiss <aaronweiss74@gmail.com>"]

[lib]

name = "sys"
crate-type = ["dylib"]

[dependencies.irc]

irc = "*"
default-features = false

[dependencies.regex]
regex = "*"

[dependencies.regex_macros]
regex_macros = "*"
