[package]
name = "snake"
version = "0.0.1"
authors = ["Aaron Weiss <aaronweiss74@gmail.com>"]

[lib]
name = "snake"
crate-type = ["dylib"]

[dependencies.irc]
irc = "*"

[dependencies.rand]
rand = "*"
