[package]
name = "tell"
version = "0.0.1"
authors = ["Aaron Weiss <aaronweiss74@gmail.com>"]

[lib]
name = "tell"
crate-type = ["dylib"]

[dependencies.irc]
version = "*"

[dependencies.rustc-serialize]
version = "*"

[dependencies.time]
version = "*"
features = ["rustc-serialize"]
