[package]

name = "tell"
version = "0.0.1"
authors = ["Aaron Weiss <aaronweiss74@gmail.com>"]

[lib]

name = "tell"
crate-type = ["dylib"]

[dependencies.irc]
irc = "*"

[dependencies.rustc-serialize]
rustc-serialize = "*"

[dependencies.time]
time = "*"
features = ["rustc-serialize"]
