[package]
name = "timefor"
version = "0.0.1"
authors = ["angelsl <angelsl@users.noreply.github.com>"]

[lib]
name = "timefor"
crate-type = ["dylib"]

[dependencies]
irc = "*"
rustc-serialize = "*"
chrono = ">= 0.2.17"
