[package]
name = "quote"
version = "0.0.1"
authors = ["Aaron Weiss <aaronweiss74@gmail.com>"]

[lib]
name = "quote"
crate-type = ["dylib"]

[dependencies.irc]
irc = "*"

[dependencies.rand]
rand = "*"

[dependencies.rustc-serialize]
rustc-serialize = "*"
