[package]

name = "keybase"
version = "0.0.1"
authors = ["Aaron Weiss <aaronweiss74@gmail.com>"]

[lib]

name = "keybase"
crate-type = ["dylib"]

[dependencies]

irc = "*"
hyper = "*"
rustc-serialize = "*"
