[package]

name = "reclaim"
version = "0.0.1"
authors = ["Aaron Weiss <aaronweiss74@gmail.com>"]

[lib]

name = "reclaim"
crate-type = ["dylib"]

[dependencies.irc]

irc = "*"
default-features = false

